export type {
  MessageData,
  TypingData,
  PresenceData,
  ReactionData,
  LivingInteraction,
  AiStreamData,
  AiStreamDone,
  ClientToServerEvents,
  ServerToClientEvents,
} from "./socket-events";

export type {
  GameData,
  GamePlayerData,
  GameConfig,
  GameState,
  GameAction,
  GameCreatedEvent,
  GameStateUpdate,
  GameFinishedEvent,
  TriviaConfig,
  TriviaState,
  TriviaQuestion,
  WordleConfig,
  WordleState,
  LetterResult,
  TicTacToeConfig,
  TicTacToeState,
  CardsConfig,
  CardsState,
} from "./game";
